gitlab:
  email:
    address: "gitlab@keyvan.home"
    displayName: "Keyvan Pishevar"
    replyTo: "noreply@redhat.com"
  smtp:
    enabled: "false"
    domain: "keyvan.home"
    host: "smtp.gitlab-gitlab.apps.sno2.keyvan.home"
    port: "587"
    user: "gitlab"
    password: "gitlab"
  ssh:
    host: "ssh.gitlab-gitlab.apps.sno2.keyvan.home"
    port: "22"
  rootPassword: openshift
  host: gitlab-gitlab.apps.sno2.keyvan.home
  https: "true"
  rootEmail: "kpisheva@redhat.com"
  keyBase:
    db: "0123456789"
    otp: "0123456789"
    secret: "0123456789"
  users:
    password: openshift
    count: 2
  groups: []
  # groups:
  # - name: backstage
  #   repo:
  #   - name: software-templates
  #     url: https://github.com/treddy08/software-templates.git

postgresql:
  dbUser: gitlab
  dbPassword: passw0rd
  dbName: gitlab_production
